# Generated by Django 2.0.6 on 2018-06-14 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('description', models.TextField(max_length=250)),
                ('age', models.IntegerField()),
                ('is_adopted', models.BooleanField(default=False)),
                ('is_castrated', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, default='images/uploads/default.png', upload_to='images/uploads')),
                ('_type', models.CharField(choices=[('cat', 'cat'), ('dog', 'dog')], max_length=10)),
            ],
            options={
                'verbose_name': 'Pet',
                'verbose_name_plural': 'Pets',
            },
        ),
        migrations.CreateModel(
            name='PetBreed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'PetBreed',
                'verbose_name_plural': 'PetsBreed',
            },
        ),
        migrations.CreateModel(
            name='PetPelage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Pelage',
                'verbose_name_plural': 'Pelages',
            },
        ),
        migrations.AddField(
            model_name='pet',
            name='breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', related_query_name='pet', to='pet.PetBreed'),
        ),
        migrations.AddField(
            model_name='pet',
            name='pelage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.PetPelage'),
        ),
    ]
