# Generated by Django 2.0 on 2018-03-21 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_petbreed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='adoted',
            new_name='is_adopted',
        ),
    ]
