# Generated by Django 2.0 on 2018-03-21 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0003_auto_20180321_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='race',
        ),
        migrations.AddField(
            model_name='pet',
            name='breed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pet.PetBreed'),
            preserve_default=False,
        ),
    ]
