# Generated by Django 2.0 on 2018-03-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0004_auto_20180321_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='_type',
            field=models.CharField(choices=[('cat', 'cat'), ('dog', 'dog')], default='dog', max_length=10),
            preserve_default=False,
        ),
    ]
