# Generated by Django 2.0 on 2018-03-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0005_pet__type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='is_castrated',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
