# Generated by Django 2.0 on 2018-03-22 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0007_pet_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', related_query_name='pet', to='pet.PetBreed'),
        ),
    ]
