# Generated by Django 2.0 on 2018-03-22 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0008_auto_20180321_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetPelage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Pelages',
                'verbose_name': 'Pelage',
            },
        ),
    ]
