# Generated by Django 2.0 on 2018-03-22 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0009_petpelage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pelage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.PetPelage'),
        ),
    ]
