# Generated by Django 2.0 on 2018-03-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0010_auto_20180321_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='petbreed',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
