# Generated by Django 2.0 on 2018-03-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0011_petbreed_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='petpelage',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
