# Generated by Django 2.0 on 2018-03-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0012_petpelage_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.IntegerField(),
        ),
    ]
