# Generated by Django 2.0 on 2018-03-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0013_auto_20180322_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='description',
            field=models.TextField(max_length=250),
        ),
    ]
