# Generated by Django 2.0 on 2018-03-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0015_pet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.ImageField(blank=True, default='images/uploads/pet_default.png', upload_to='images/uploads'),
        ),
    ]
