# Generated by Django 2.0 on 2018-03-27 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0016_auto_20180323_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.ImageField(blank=True, default='images/uploads/default.png', upload_to='images/uploads'),
        ),
    ]
