# Generated by Django 2.0 on 2018-06-12 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0017_auto_20180327_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='is_adopted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pet',
            name='is_castrated',
            field=models.BooleanField(default=False),
        ),
    ]
